/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frame;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import report.ReportLaporanPembayaran;
import tools.ComboItem;
import tools.MysqlConnect;

/**
 *
 * @author Wahyu
 */
public class FrameLaporanSPP extends javax.swing.JInternalFrame {
FrameMain frameMain;
// Inisialisasi Database
MysqlConnect mysqlConnect = new MysqlConnect();
ResultSet rs;
Statement st;
// inisialisasi variabel
private int kelas=0;
private String pembayaran_bulan="";
// inisalisasi combobox vector
Vector Kelasmodel = new Vector();  
    public FrameLaporanSPP(FrameMain frameMain) {
        this.frameMain = frameMain;
        setVisible(true);
        mysqlConnect.createDatabase(); // Buka Database
        try{
        st = mysqlConnect.conn.createStatement();
        }
        catch(SQLException ex){}
        initComponents();
        JKelas();
        JTanggal();
    }
    
    private void JKelas(){
       try{
       String sql ="select * from kelas order by CAST(nama_kelas as SIGNED INTEGER) ASC";
       rs = st.executeQuery(sql); // meload query

       rs.beforeFirst();
       Kelasmodel.addElement(new ComboItem(0,"Pilih Kelas"));
       while(rs.next()){
           Kelasmodel.addElement(new ComboItem(rs.getInt("id_kelas"),rs.getString("nama_kelas")));
       }
         cKelas.setModel(new javax.swing.DefaultComboBoxModel(Kelasmodel));
       }
       catch(SQLException ex){}
    } 
    
    private void JTanggal(){
        cBulan.addItem("Bulan");
        cTahun.addItem("Tahun");
        for(int bln=1;bln<=12;bln++){
            if(bln==1){cBulan.addItem("Januari");}
            else if(bln==2){cBulan.addItem("Februari");}
            else if(bln==3){cBulan.addItem("Maret");}
            else if(bln==4){cBulan.addItem("April");}
            else if(bln==5){cBulan.addItem("Mei");}
            else if(bln==6){cBulan.addItem("Juni");}
            else if(bln==7){cBulan.addItem("Juli");}
            else if(bln==8){cBulan.addItem("Agustus");}
            else if(bln==9){cBulan.addItem("September");}
            else if(bln==10){cBulan.addItem("Oktober");}
            else if(bln==11){cBulan.addItem("November");}
            else if(bln==12){cBulan.addItem("Desember");}
        }
        Calendar now = Calendar.getInstance();
        int year = now.get(Calendar.YEAR);
        for(int tgl=(year-2);tgl<=(year+2);tgl++){
        cTahun.addItem(tgl);
        }
    }
    
    private void print(){
       ComboItem itemKelas = (ComboItem)cKelas.getSelectedItem();
       kelas = (int)itemKelas.getId();
       
       int tahun;

       String bulan = (String) cBulan.getSelectedItem();
       String bln="";
       if(bulan.equals("Januari")){bln="01";}else if(bulan.equals("Februari")){bln="02";}
       else if(bulan.equals("Maret")){bln="03";}else if(bulan.equals("April")){bln="04";}
       else if(bulan.equals("Mei")){bln="05";}else if(bulan.equals("Juni")){bln="06";}
       else if(bulan.equals("Juli")){bln="07";}else if(bulan.equals("Agustus")){bln="08";}
       else if(bulan.equals("September")){bln="09";}else if(bulan.equals("Oktober")){bln="10";}
       else if(bulan.equals("November")){bln="11";}else if(bulan.equals("Desember")){bln="12";}
       
       
       if(kelas==0){
           JOptionPane.showMessageDialog(null,"Anda Belum pilih kelas");
           cKelas.requestFocus();
       }
       else if(bulan.equals("Bulan")){
           JOptionPane.showMessageDialog(null,"Anda Belum pilih bulan pembayaran");
           cBulan.requestFocus();
       }
       else if(cTahun.getSelectedItem().equals("Tahun")){
       JOptionPane.showMessageDialog(null,"Anda Belum pilih tahun pembayaran");
       cTahun.requestFocus();
       }
       else{
               tahun = (int) cTahun.getSelectedItem(); 
               pembayaran_bulan = tahun+"-"+bln+"-"+01;
               new ReportLaporanPembayaran(kelas,pembayaran_bulan);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cKelas = new javax.swing.JComboBox();
        cBulan = new javax.swing.JComboBox();
        cTahun = new javax.swing.JComboBox();
        Print = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Laporan SPP");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        jPanel1.add(cKelas);

        jPanel1.add(cBulan);

        jPanel1.add(cTahun);

        Print.setText("Cetak Laporan");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jPanel1.add(Print);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        frameMain.setTampilJFrameLaporanSPP(false);
    }//GEN-LAST:event_formInternalFrameClosed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        print();
    }//GEN-LAST:event_PrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Print;
    private javax.swing.JComboBox cBulan;
    private javax.swing.JComboBox cKelas;
    private javax.swing.JComboBox cTahun;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
